import withSidebarLayout from "../common/sidebar/withSidebarLayout";
import Dashboard from "./dashboard/dashboard";
import ConnectionDashboard from "./dashboard/ConnectionDashboard";
import AffiliateDashboard from "./affiliate/affiliateDashboard/AffiliateDashboard";
import NewAffiliate from "./affiliate/AffiliateDashboardNew/AffiliateDashboard";
import AffiliateLinks from "./affiliate/affiliateLinks/affiliateLinks";
import AffiliateSettings from "./affiliate/settings/affiliateSettings";
import LevelCommission from "./affiliate/level-commissions/levelCommission";
import Crm from "./fb/crm/Crm";
import IgCrm from "./ig/crm/Crm";
import Birthday from "./fb/birthday/Birthday";
import FriendsList from "./fb/friends-list/FriendsList";
import Request from "./fb/request/Request";
import MessageIndex from "./library/message/messageIndex";
import FbProspecting from "./fb/prospecting/index";
import IgProspecting from "./ig/prospecting/index";
import Unfriended from "./fb/friends-list/Unfriended";
import Deactivated from "./fb/friends-list/Deactivated";
import Whitelist from "./fb/friends-list/Whitelist";
import AiComments from "./ai-comments/AiComments";
import Keywords from "./library/keyword/keyword";
import Profile from "./profile/index";
import Upgrade from "./upgade/upgarde";

const DashboardPage = withSidebarLayout(Dashboard);
const ConnectionDashboardPage = withSidebarLayout(ConnectionDashboard);
const AffiliatePage = withSidebarLayout(AffiliateDashboard);
const NewAffiliatePage = withSidebarLayout(NewAffiliate);
const AffiliateLinksPage= withSidebarLayout(AffiliateLinks);
const LevelCommissionPage = withSidebarLayout(LevelCommission);
const AffiliateSettingsPage = withSidebarLayout(AffiliateSettings);
const FbProspectingPage = withSidebarLayout(FbProspecting);
const IgProspectingPage = withSidebarLayout(IgProspecting);
const CrmPage = withSidebarLayout(Crm);
const BirthdayPage = withSidebarLayout(Birthday);
const FriendsPage = withSidebarLayout(FriendsList);
const RequestPage = withSidebarLayout(Request);
const MessageIndexPage = withSidebarLayout(MessageIndex);
const UnfriendedPage = withSidebarLayout(Unfriended);
const DeactivatedPage = withSidebarLayout(Deactivated);
const WhitelistPage = withSidebarLayout(Whitelist);
const IgCrmPage = withSidebarLayout(IgCrm);
const AiCommentsPage = withSidebarLayout(AiComments);
const KeywordsPage = withSidebarLayout(Keywords);
const ProfilePage = withSidebarLayout(Profile);
const UpgradePage = withSidebarLayout(Upgrade);

export { DashboardPage, AffiliatePage, AffiliateLinksPage, LevelCommissionPage, AffiliateSettingsPage, CrmPage, BirthdayPage, FriendsPage, RequestPage, MessageIndexPage, IgCrmPage, AiCommentsPage, UnfriendedPage, DeactivatedPage, WhitelistPage, KeywordsPage, ConnectionDashboardPage, FbProspectingPage, IgProspectingPage, ProfilePage, NewAffiliatePage,UpgradePage }